#!/bin/bash

BASEPATH=".githooks/pre-push.d"

REMOTE=$1
URL=$2

while read local_ref local_sha remote_ref remote_sha
do
    for filename in $(ls -1 "$BASEPATH")
    do
        "$BASEPATH/$filename" $REMOTE $URL $local_ref $local_sha $local_ref $local_sha
        RESULT=$?
        if [ $RESULT -ne 0 ]; then
            exit $RESULT
        fi
    done
done

exit 0
