[package]
name = "hiriluk-python"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "_hiriluk"
crate-type = ["cdylib"]

[dependencies]
hiriluk = { path = "../.." }
numpy = "0.29.0"
pyo3 = { version = "0.29.0", features = ["abi3-py310", "extension-module"] }
